disable -Werror due to aliasing problems rejected by gcc 4.4.6 / RHEL6.2
cc1: warnings being treated as errors
./common/lpd_dispatch.c: In function 'Service_connection':
./common/lpd_dispatch.c:210: error: dereferencing pointer 'sinaddr.54' does break strict-aliasing rules
./common/lpd_dispatch.c:210: note: initialized from here